### ISSUE TITLE
Rich Presence not showing in Discord

### ISSUE THREAD

**Issue by M1918IIBAR** [Zanzancomms/Genshin-Impact-Rich-Presence#2]
The program runs fine without any errors but the rich presence doesn't seem to be showing in discord. am I missing a step in the tutorial?

**Comment by Zanzancomms** [comment]
havent opened the rich presence in a while since i dont play as much now but will see if mine works still and troubleshoot your issue

**Comment by Zanzancomms** [comment]
also when opening the rich presence, make sure you dont close the cmd console thing thats what makes the rich presence happen o/

**Comment by Zanzancomms** [comment]
ah right i also removed the release for the latest one now that i see
should have that but the latest doesnt, so think that would be why ![image](https://user-images.githubusercontent.com/68141931/179273173-c6bd73eb-4317-419c-92a8-b103a5311670.png)

**Comment by Zanzancomms** [comment]
anyway ill troubleshoot it now, i was downloading latest and fixing other things

**Comment by Zanzancomms** [comment]
ill make a new release in a bit

**Comment by M1918IIBAR** [comment]
alright thank you so much

**Comment by M1918IIBAR** [comment]
alright it works now thank you
